name: Release
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
    
jobs:
  build_artifact:
    name: Build and upload artifact
    if: github.repository == 'awslabs/cdk8s'
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain
    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: tools/install-workflow-deps.sh
      - name: set version
        run: tools/align-version.sh
      - name: compile
        run: yarn build
      - name: unit tests
        run: yarn test
      - name: create bundle
        run: yarn package
      - name: integration tests
        run: yarn integ
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: Release to github
        run: yarn release-github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
